language: python

python:
    - 2.6
    - 2.7

env: 
    - DJANGO="Django==1.7.1"

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - cd behavui; coverage run manage.py test

after_success:
    - coveralls
