language: python

python:
    - 3.3

env: 
    - DJANGO="Django==1.7.1"

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - coverage run --rcfile=.coveragerc ./behavui/manage.py test

after_success:
    - coveralls --rcfile=.coveragerc
